/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import DB.Conexion;
import codigo.fondoN;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.swing.JOptionPane;
import static ventanas.contrasenaC.txtrecibi;
import static ventanas.menu.txtSald;


/**
 *
 * @author Manucho
 */
public class AgregarFondos extends javax.swing.JFrame {
     Conexion conec=new Conexion();
Connection conectar=conec.conectar();
    public double total; 
    public String textTotal;
    public double ret;
    public String sal;
    
    

    
    
   
    
    /**
     * Creates new form Retirar
     */
    public AgregarFondos() {
        initComponents();
        transparencia();
        setLocationRelativeTo(null);
        txtMonto.setBackground(new java.awt.Color(0,0,0,1));
        
    }
    
    public void transparencia(){
    bille5.setOpaque(false);
    bille5.setContentAreaFilled(false);
    bille5.setBorderPainted(false);
    
    bille10.setOpaque(false);
    bille10.setContentAreaFilled(false);
    bille10.setBorderPainted(false);
    
    bille20.setOpaque(false);
    bille20.setContentAreaFilled(false);
    bille20.setBorderPainted(false);
    
    bille50.setOpaque(false);
    bille50.setContentAreaFilled(false);
    bille50.setBorderPainted(false);
    
    bille100.setOpaque(false);
    bille100.setContentAreaFilled(false);
    bille100.setBorderPainted(false);
    
    bille200.setOpaque(false);
    bille200.setContentAreaFilled(false);
    bille200.setBorderPainted(false);
    
    btnBorrar.setOpaque(false);
    btnBorrar.setContentAreaFilled(false);
    btnBorrar.setBorderPainted(false);
    
    jButton1.setOpaque(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setBorderPainted(false);
    
    jButton2.setOpaque(false);
    jButton2.setContentAreaFilled(false);
    jButton2.setBorderPainted(false);
    
     
    
    
    
    
  
    }
    
    public void conv(){
    
    }
    public void Suma(){
        sal=txtSald.getText();
        ret=Double.parseDouble(sal);
        
       total = ret + total;
       
    }
        
    
   public void ModificarDatos(){
       Suma();
        try {
        PreparedStatement pasar=conectar.prepareStatement("UPDATE cuenta SET saldo='"+total+"' WHERE cuenta='"+txtrecibi.getText()+"'");
        pasar.executeUpdate();
        JOptionPane.showMessageDialog(null, "Se han agregado fondos satisfactoriamente...");
        menu m=new menu();
        m.setVisible(true);
        dispose();
        
        
    } catch (SQLException ex) {
        Logger.getLogger(crearC.class.getName()).log(Level.SEVERE, null, ex);
    }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fondoN(this);
        bille5 = new javax.swing.JButton();
        bille10 = new javax.swing.JButton();
        bille20 = new javax.swing.JButton();
        bille50 = new javax.swing.JButton();
        bille100 = new javax.swing.JButton();
        bille200 = new javax.swing.JButton();
        txtMonto = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bille5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/bi5.png"))); // NOI18N
        bille5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/bi5.png"))); // NOI18N
        bille5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/5p.png"))); // NOI18N
        bille5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bille5ActionPerformed(evt);
            }
        });

        bille10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/bi10.png"))); // NOI18N
        bille10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/bi10.png"))); // NOI18N
        bille10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/10p.png"))); // NOI18N
        bille10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bille10ActionPerformed(evt);
            }
        });

        bille20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/bi20.png"))); // NOI18N
        bille20.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/bi20.png"))); // NOI18N
        bille20.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/20p.png"))); // NOI18N
        bille20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bille20ActionPerformed(evt);
            }
        });

        bille50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/bi50.png"))); // NOI18N
        bille50.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/bi50.png"))); // NOI18N
        bille50.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/50p.png"))); // NOI18N
        bille50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bille50ActionPerformed(evt);
            }
        });

        bille100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/bi100.png"))); // NOI18N
        bille100.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/bi100.png"))); // NOI18N
        bille100.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/100p.png"))); // NOI18N
        bille100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bille100ActionPerformed(evt);
            }
        });

        bille200.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/bi200.png"))); // NOI18N
        bille200.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/bi200.png"))); // NOI18N
        bille200.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/billetes/200p.png"))); // NOI18N
        bille200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bille200ActionPerformed(evt);
            }
        });

        txtMonto.setFont(new java.awt.Font("Bungee Inline", 1, 48)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(23, 58, 98));
        txtMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMonto.setBorder(null);
        txtMonto.setFocusable(false);
        txtMonto.setOpaque(false);
        txtMonto.setRequestFocusEnabled(false);
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/basura.png"))); // NOI18N
        btnBorrar.setPreferredSize(new java.awt.Dimension(64, 64));
        btnBorrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/basura.png"))); // NOI18N
        btnBorrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BORRARp_1.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bungee", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(23, 58, 98));
        jLabel1.setText("MONTO");

        jLabel2.setFont(new java.awt.Font("Bungee", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 190, 231));
        jLabel2.setText("DE ");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CANCELAR.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(77, 25));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CANCELAR.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelarP.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ACEPTAR.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(77, 24));
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ACEPTAR.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ACEPTARp.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bungee", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(33, 190, 231));
        jLabel3.setText("Seleccione el tipo");

        jLabel4.setFont(new java.awt.Font("Bungee", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 190, 231));
        jLabel4.setText("BILLETE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bille20, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bille100, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bille200, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bille50, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bille5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(bille10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bille5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bille20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bille100, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bille10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bille50, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bille200, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bille5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bille5ActionPerformed
     total = total + 5; 
     mostrarSum();
     
    }//GEN-LAST:event_bille5ActionPerformed

    private void bille10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bille10ActionPerformed
    total = total + 10;
    mostrarSum();
    }//GEN-LAST:event_bille10ActionPerformed

    private void bille20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bille20ActionPerformed
    total = total + 20;     
    mostrarSum();
    }//GEN-LAST:event_bille20ActionPerformed

    private void bille50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bille50ActionPerformed
    total = total + 50;     
    mostrarSum();
    }//GEN-LAST:event_bille50ActionPerformed

    private void bille100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bille100ActionPerformed
    total = total + 100; 
    mostrarSum();
    }//GEN-LAST:event_bille100ActionPerformed

    private void bille200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bille200ActionPerformed
    total = total + 200;   
    mostrarSum();
    
    }//GEN-LAST:event_bille200ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        total = 0;
        txtMonto.setText("");
        
        
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        int salida = JOptionPane.showConfirmDialog(null, "Desea cancelar la transacción");
        if (salida==0) {
            menu sal = new menu();
            sal.setVisible(true);
            dispose();
            total = 0;
            txtMonto.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
ModificarDatos();             // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarFondos().setVisible(true);
            }
        });
    }
    
    public void addBillete(String digito){
    //txtOpe.setText(txtOpe.getText() + digito);
    }

    public void mostrarSum(){
    System.out.println(total);
    textTotal = String.valueOf(total);
    txtMonto.setText("");
    txtMonto.setText(textTotal+ " Q");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bille10;
    private javax.swing.JButton bille100;
    private javax.swing.JButton bille20;
    private javax.swing.JButton bille200;
    private javax.swing.JButton bille5;
    private javax.swing.JButton bille50;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
